# Generated by Django 4.2.3 on 2023-07-30 13:33

import app1.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_alter_finepage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finepage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=app1.models.upload_to),
        ),
    ]
