# Generated by Django 4.2.3 on 2023-07-31 02:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_finepage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finepage',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/', validators=[django.core.validators.validate_image_file_extension]),
        ),
    ]
