# Generated by Django 4.2.3 on 2023-07-31 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_finepage_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='finepage',
            name='bio',
            field=models.CharField(default='lol', max_length=100),
            preserve_default=False,
        ),
    ]
