# Generated by Django 4.2.3 on 2023-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_finepage_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='finepage',
            name='url_field',
            field=models.URLField(default='https://goo.gl/maps/NY5TGrDPH9BZPBE5'),
            preserve_default=False,
        ),
    ]
