# Generated by Django 4.2.3 on 2023-08-04 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_finepage_url_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finepage',
            name='url_field',
            field=models.URLField(max_length=500),
        ),
    ]
