# Generated by Django 4.2.4 on 2023-08-27 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_finepage_latitude_finepage_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finepage',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='finepage',
            name='longitude',
        ),
        migrations.AddField(
            model_name='finepage',
            name='ur_rl',
            field=models.URLField(default='none', max_length=8000),
            preserve_default=False,
        ),
    ]
